host: 'https://wri-01.cartodb.com'
oauth_key: 'TJxdluIfO1vCXj2isspBN1FYgnLBXsatvQe5FXa3'
oauth_secret: 'hsPxXKhDvxW7fwDG90PLCfuvtkQarPMiUBHuQFPv'
username: 'wri-01'
password: 'YZajArN7'

heroku config:add host='https://wri-01.cartodb.com' oauth_key='TJxdluIfO1vCXj2isspBN1FYgnLBXsatvQe5FXa3' username='wri-01' password='YZajArN7'
